### PR TITLE
install_vim: fix some issues reported by shellcheck

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by tweekmonster** [comment]
Thanks!  I guess shellcheck should be included in the travis build as well.

**Comment by blueyed** [comment]
> I guess shellcheck should be included in the travis build as well.

It is more for linting shell scripts, and not Vim scripts.
But `vint` (or `vimlint`) might be useful to have by default.

**Comment by tweekmonster** [comment]
> It is more for linting shell scripts, and not Vim scripts.

I was thinking it'd be for checking PRs.  OTOH, this repo should be fairly low maintenance.

> But vint (or vimlint) might be useful to have by default.

Do you mean as part of the image?

**Comment by blueyed** [comment]
> I was thinking it'd be for checking PRs.

Ah, makes sense.

> Do you mean as part of the image?

Yes.

**Pull request merged**
